package controllers.job

/**
 * Created by vinaysaini on 10/7/15.
 */
object IndeedApi {

  val INDEED_API_DEFAULT_COUNTRIES = Array("ae", "aq", "ar", "at", "au", "be", "bh", "br", "ca", "ch", "cl", "cn", "co", "cz", "de", "dk", "es", "fi", "fr", "gb", "gr", "hk", "hu", "id", "ie", "il", "in", "it", "jp", "kr", "kw", "lu", "mx", "my", "nl", "no", "nz", "om", "pe", "ph", "pk", "pl", "pt", "qa", "ro", "ru", "sa", "se", "sg", "th", "tr", "tw", "us", "ve", "vn", "za")

  val INDEED_API_DEFAULT_LOCALE = Map("cn" -> "zh-cn", "de" -> "de", "es" -> "es", "gb" -> "en", "fr" -> "fr", "it" -> "it", "nl" -> "nl", "pl" -> "pl", "pt" -> "pr", "us" -> "en")

  val LOCATION_PER_COUNTRY = Map(
    "ae" -> Array("AJ", "AZ", "DU", "FU", "RK", "S04", "SH", "UQ"),
    "af" -> Array("HER", "KAB", "NUR", "PAR", "WAR"),
    "aq" -> Array("A00"),
    "ar" -> Array("A", "B", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"),
    "at" -> Array("B", "BY", "K", "N", "O", "SA", "ST", "T", "V", "W"),
    "au" -> Array("ACT", "CX", "NF", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"),
    "be" -> Array("A8", "BRU", "BW", "VLG", "WAL"),
    "bh" -> Array("B13", "B14", "B15", "B16", "B17"),
    "br" -> Array("AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "IF", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO"),
    "ca" -> Array("AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "OH", "ON", "OR", "PE", "QC", "SK", "VT", "YT"),
    "ch" -> Array("AG", "AI", "AR", "BE", "BL", "BS", "CT", "FR", "GE", "GL", "GR", "JU", "LI", "LU", "NE", "NW", "OW", "SG", "SH", "SO", "SZ", "TG", "TI", "UR", "VD", "VS", "ZG", "ZH"),
    "cl" -> Array("AI", "AN", "AP", "AR", "AT", "BI", "CO", "LI", "LL", "LR", "MA", "ML", "RM", "TA", "VS"),
    "cn" -> Array("A8", "AN", "BW", "BY", "C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10", "C11", "C12", "C13", "C14", "C15", "C16", "C18", "C19", "C20", "C21", "C22", "C23", "C24", "C25", "C26", "C28", "C29", "C30", "C31", "C32", "C33", "IL", "MA", "MI", "WAL"),
    "co" -> Array("AMA", "ANT", "ARA", "ATL", "BOL", "BOY", "CAL", "CAQ", "CAS", "CAU", "CES", "CHO", "COR", "CUN", "GUA", "GUV", "HUI", "LAG", "MAG", "MET", "NAR", "NSA", "PUT", "QUI", "RIS", "SAN", "SAP", "SUC", "TOL", "VAC", "VAU", "VID"),
    "cz" -> Array("IF", "JC", "JM", "KA", "KR", "LI", "ML", "MO", "OL", "PA", "PL", "ST", "US", "VY", "ZL"),
    "de" -> Array("A8", "AN", "B", "BB", "BE", "BW", "BY", "C12", "GRI", "HB", "HE", "HH", "K", "M", "MI", "MV", "NI", "NW", "RP", "SA", "SH", "SL", "SN", "ST", "TH", "TN"),
    "dk" -> Array("D81", "D82", "D83", "D84", "D85", "FO", "GL"),
    "eg" -> Array("AJ", "S01", "TX"),
    "es" -> Array("A8", "AD", "AN", "AR", "AS", "B5", "BW", "BY", "C12", "CB", "CE", "CL", "CM", "CN", "CT", "EX", "GA", "IB", "IN", "MC", "MD", "MI", "ML", "NC", "PV", "RI", "T35", "VC"),
    "fi" -> Array("F01", "F02", "F03", "F04", "F05", "F06", "F07", "F08", "F09", "F10", "F11", "F12", "F13", "F14", "F15", "F16", "F17", "F18", "F19", "F20", "WV"),
    "fr" -> Array("97", "98", "99", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AN", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BW", "C1", "C12", "C30", "DE", "DTM", "MI", "N", "NI", "VLG"),
    "gb" -> Array("A4", "CHA", "EA", "EM", "NE", "NIR", "NW", "SCT", "SE", "SW", "T2", "WLS", "WM", "YH"),
    "gr" -> Array("GRA", "GRB", "GRC", "GRD", "GRE", "GRF", "GRG", "GRH", "GRI", "GRJ", "GRK", "GRL", "GRM", "ZA"),
    "hk" -> Array("HKI", "KOW", "NT"),
    "hr" -> Array("H13"),
    "hu" -> Array("BA", "BE", "BK", "BZ", "CS", "FE", "GS", "HB", "HE", "JN", "KE", "NO", "PE", "SO", "SZ", "TO", "VA", "VE", "ZA"),
    "id" -> Array("AC", "BA", "BB", "BE", "BT", "GO", "JA", "JB", "JI", "JK", "JT", "KB", "KI", "KR", "KS", "KT", "LA", "MA", "MU", "NB", "NT", "PA", "PB", "RI", "SA", "SB", "SG", "SN", "SR", "SS", "ST", "SU", "YO"),
    "ie" -> Array("C", "CE", "CN", "CW", "D", "DL", "ENG", "G", "KE", "KK", "KY", "LD", "LH", "LK", "LM", "LS", "MH", "MN", "MO", "ON", "OY", "RN", "SCT", "SO", "TA", "WD", "WH", "WLS", "WW", "WX"),
    "il" -> Array("BY", "H", "HA", "IN", "JM", "M", "TA", "UP", "Z"),
    "in" -> Array("AN", "AP", "AR", "AS", "BR", "CH", "CT", "DD", "DL", "DN", "GA", "GJ", "HP", "HR", "JH", "JK", "KA", "KL", "LD", "M", "MH", "ML", "MN", "MP", "MZ", "NL", "OR", "PB", "PY", "RJ", "SK", "TN", "TR", "TS", "UL", "UP", "WB"),
    "it" -> Array("ABR", "BAS", "CAL", "CAM", "EMI", "FRI", "LAZ", "LIG", "LOM", "MAR", "MOL", "PIE", "PUG", "SAR", "SIC", "TOS", "TRE", "UMB", "VAL", "VEN"),
    "jp" -> Array("AN", "JPA", "JPB", "JPC", "JPD", "JPE", "JPF", "JPG", "JPH", "JPI"),
    "kp" -> Array("HAN"),
    "kr" -> Array("1", "3", "5", "6", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"),
    "kw" -> Array("AH", "FA", "HA", "JA", "KU", "MU"),
    "lu" -> Array("L0D", "L0G", "L0L"),
    "ma" -> Array("B9"),
    "mx" -> Array("AGU", "BCN", "BCS", "CAM", "CHH", "CHP", "COA", "COL", "DIF", "DUR", "GRO", "GUA", "HID", "JAL", "MEX", "MIC", "MOR", "NAY", "NLE", "OAX", "PUE", "QUE", "ROO", "SIN", "SLP", "SON", "TAB", "TAM", "TLA", "VER", "YUC", "ZAC"),
    "my" -> Array("M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11", "M12", "M13", "M14", "M15", "M16"),
    "nl" -> Array("AN", "DR", "ENG", "FL", "FR", "GE", "GR", "LI", "NB", "NH", "OV", "UT", "ZE", "ZH"),
    "no" -> Array("ENG", "N01", "N02", "N03", "N04", "N05", "N06", "N07", "N08", "N09", "N10", "N11", "N12", "N14", "N15", "N16", "N17", "N18", "N19", "N20", "N21"), "nz" -> Array("CK", "N", "S", "TK"),
    "om" -> Array("BA", "BU", "DA", "JA", "MA", "MU", "SH", "WU", "ZA"),
    "pe" -> Array("AMA", "ANC", "APU", "ARE", "AYA", "CAJ", "CAL", "CUS", "HCL", "HNC", "ICA", "JUN", "LAM", "LIM", "LLI", "LOR", "MDD", "MOQ", "PAS", "PIU", "PUN", "SMA", "TAC", "TUM", "UCA"),
    "ph" -> Array("04A", "04B", "P00", "P01", "P02", "P03", "P05", "P06", "P07", "P08", "P09", "P10", "P11", "P12", "P13", "P14", "P15"),
    "pk" -> Array("PB", "PBA", "PIS", "PJK", "PNA", "PNW", "PPB", "PSD", "PTA"),
    "pl" -> Array("DO", "KP", "LL", "LO", "LU", "ML", "MZ", "NW", "OP", "PL", "PM", "PP", "SL", "SW", "T34", "WM", "WP", "ZA"),
    "pt" -> Array("BB", "ENG", "P01", "P02", "P03", "P04", "P05", "P06", "P07", "P08", "P09", "P10", "P11", "P12", "P13", "P14", "P15", "P16", "P17", "P18", "P20", "P30"),
    "qa" -> Array("DAW", "JAR", "JUM", "KHA", "MUS", "RAY", "SHA", "UMM", "WAK"),
    "ro" -> Array("AB", "AG", "AR", "BC", "BH", "BN", "BR", "BT", "BV", "BZ", "CJ", "CL", "CS", "CT", "CV", "DB", "DJ", "ENG", "GJ", "GL", "GR", "HD", "HR", "IF", "IL", "IS", "MH", "MM", "MS", "NT", "OT", "PH", "SB", "SJ", "SM", "SV", "TL", "TM", "TR", "VL", "VN", "VS"),
    "ru" -> Array("CEN", "CRI", "DAL", "JUZ", "PRV", "SIB", "SKA", "SZA", "URA"),
    "sa" -> Array("S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10", "S11", "S12", "S14"),
    "se" -> Array("AB", "AC", "BD", "C", "D", "E", "F", "G", "H", "I", "K", "M", "N", "O", "S", "T", "U", "W", "X", "Y", "Z"),
    "sg" -> Array("S00", "TN"),
    "si" -> Array("SC9"),
    "th" -> Array("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "60", "61", "62", "63", "64", "65", "66", "67", "70", "71", "72", "73", "74", "75", "76", "77", "80", "81", "82", "83", "84", "85", "86", "90", "91", "92", "93", "94", "95", "96"),
    "tr" -> Array("AR", "IF", "LO", "T01", "T02", "T03", "T04", "T05", "T06", "T07", "T08", "T09", "T10", "T11", "T12", "T13", "T14", "T15", "T16", "T17", "T18", "T19", "T20", "T21", "T22", "T23", "T24", "T25", "T26", "T27", "T28", "T29", "T30", "T31", "T32", "T33", "T34", "T35", "T36", "T37", "T38", "T39", "T40", "T41", "T42", "T43", "T44", "T45", "T46", "T47", "T48", "T49", "T50", "T51", "T52", "T53", "T54", "T55", "T56", "T57", "T58", "T59", "T60", "T61", "T62", "T63", "T64", "T65", "T66", "T67", "T68", "T69", "T70", "T71", "T72", "T73", "T74", "T75", "T76", "T77", "T78", "T79", "T80", "T81", "TX"),
    "tw" -> Array("CHA", "CYI", "CYQ", "HSQ", "HSZ", "HUA", "ILA", "KEE", "KHH", "MIA", "NAN", "PEN", "PIF", "TAO", "TNN", "TPE", "TPQ", "TTT", "TXG", "YUN"),
    "ua" -> Array("CEN"),
    "us" -> Array("99", "A8", "AB", "AK", "AL", "AN", "AR", "AS", "AZ", "B2", "B5", "B9", "BC", "BW", "CA", "CO", "CT", "D84", "DC", "DE", "ENG", "F19", "FL", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "JPC", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MP", "MS", "MT", "NC", "ND", "NE", "NH", "NIR", "NJ", "NM", "NV", "NW", "NY", "OH", "OK", "ON", "OR", "PA", "PR", "RI", "SC", "SD", "T34", "TN", "TX", "UM", "UT", "VA", "VI", "VT", "WA", "WI", "WV", "WY", "ZA"),
    "ve" -> Array("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"),
    "vn" -> Array("1", "13", "14", "18", "2", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "3", "30", "31", "32", "33", "34", "35", "36", "37", "39", "4", "40", "41", "43", "44", "45", "46", "47", "49", "5", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "6", "61", "63", "66", "67", "68", "69", "7", "70", "71", "72", "73", "9", "CT", "DN", "HN", "HP", "SG"),
    "za" -> Array("EC", "FS", "GP", "LP", "MP", "NC", "NW", "WC", "ZN")
  )

  val INDEED_SOURCE_TRACKING_TOKEN = Map(
    "25147"  -> "&tSource=a169000000090xAAAQ",
    "13215"  -> "?feedId=85600&utm_source=Indeed&utm_campaign=ATK_Indeed",
    "328615" -> "aaJob Board | Indeed.com",
    "22211"  -> "&s=Indeed",
    "1411"   -> "?feedId=1434&utm_source=Indeed&sourceType=PREMIUM_POST_SITE&source=INDEED",
    "3379"   -> "&jobPipeline=Indeed",
    "8701"   -> "?apstr=%26sid%3D60&utm_source=Indeed&utm_medium=organic&utm_campaign=Indeed",
    "5805"   -> "apstr=src%3DJB-12021",
    "17122"  -> "?apstr=source%3DIndeed.com",
    "38066"  -> "&electronic_referral=indeed"
  )

  val BASE_URL_PER_COUNTRY = Map(
    "ae"->"http://www.indeed.ae",
    "aq"->"http://aq.indeed.com",
    "ar"->"http://ar.indeed.com",
    "at"->"http://at.indeed.com",
    "au"->"http://au.indeed.com",
    "be"->"http://be.indeed.com",
    "bh"->"http://bh.indeed.com",
    "br"->"http://www.indeed.com.br",
    "ca"->"http://ca.indeed.com",
    "ch"->"http://www.indeed.ch",
    "cl"->"http://www.indeed.cl",
    "cn"->"http://cn.indeed.com",
    "co"->"http://co.indeed.com",
    "cz"->"http://cz.indeed.com",
    "de"->"http://de.indeed.com",
    "dk"->"http://dk.indeed.com",
    "es"->"http://www.indeed.es",
    "fi"->"http://www.indeed.fi",
    "fr"->"http://www.indeed.fr",
    "gb"->"http://www.indeed.co.uk",
    "gr"->"http://gr.indeed.com",
    "hk"->"http://www.indeed.hk",
    "hu"->"http://hu.indeed.com",
    "id"->"http://id.indeed.com",
    "ie"->"http://ie.indeed.com",
    "il"->"http://il.indeed.com",
    "in"->"http://www.indeed.co.in",
    "it"->"http://it.indeed.com",
    "jp"->"http://jp.indeed.com",
    "kr"->"http://kr.indeed.com",
    "kw"->"http://kw.indeed.com",
    "lu"->"http://www.indeed.lu",
    "mx"->"http://www.indeed.com.mx",
    "my"->"http://www.indeed.com.my",
    "nl"->"http://www.indeed.nl",
    "no"->"http://no.indeed.com",
    "nz"->"http://nz.indeed.com",
    "om"->"http://om.indeed.com",
    "pe"->"http://www.indeed.com.pe",
    "ph"->"http://www.indeed.com.ph",
    "pk"->"http://www.indeed.com.pk",
    "pl"->"http://pl.indeed.com",
    "pt"->"http://www.indeed.pt",
    "qa"->"http://qa.indeed.com",
    "ro"->"http://ro.indeed.com",
    "ru"->"http://ru.indeed.com",
    "sa"->"http://sa.indeed.com",
    "se"->"http://se.indeed.com",
    "sg"->"http://www.indeed.com.sg",
    "th"->"http://th.indeed.com",
    "tr"->"http://tr.indeed.com",
    "tw"->"http://tw.indeed.com",
    "us"->"http://www.indeed.com",
    "ve"->"http://ve.indeed.com",
    "vn"->"http://vn.indeed.com",
    "za"->"http://www.indeed.co.za"
  )
  val INDEED_API_PUBLISHER_ID = "24719483804451"
}
